### ISSUE TITLE
ContextErrorException in Halstead.php line 55

### ISSUE THREAD

**Issue by ghost** [phpmetrics/PhpMetricsCollectorBundle#4]
Hi 
I have some problems with bundle, I recieve ContextErrorException right after installation.

ContextErrorException in Halstead.php line 55: Catchable Fatal Error: Argument 1 passed to Hal\Metrics\Complexity\Text\Halstead\Halstead::__construct() must be an instance of Hal\Component\Token\TokenType, instance of Hal\Component\Token\Tokenizer given, called in vendor/halleck45/phpmetrics-collector-bundle/src/Hal/Bundle/PhpMetricsCollector/Collector/PhpMetricsCollector.php on line 51 and defined

I hope you can help me with it.

**Comment by Halleck45** [comment]
I close issue due to inactivity. Feel free to open it again if needed :)
